name: Deploy Cloud Functions
on:
  workflow_dispatch:
  push:
    branches:
      - qa
      - staging
      - main
    paths:
      - "functions/**"
env:
  FIREBASE_SERVICE_ACCOUNT: undefined
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars (qa)
        if: endsWith(github.ref, '/qa')
        run: |
          echo 'FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT_QA }}' >> $GITHUB_ENV
      - name: Set env vars (staging)
        if: endsWith(github.ref, '/staging')
        run: |
          echo 'FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}' >> $GITHUB_ENV
      - name: Set env vars (prod)
        if: endsWith(github.ref, '/main')
        run: |
          echo 'FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROD }}' >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build Cloud Functions
        run: npm ci
        working-directory: functions
      - name: Create SA key
        run: echo '${{ env.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/gcloud.json
      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json